#!/bin/bash -e
#
# Copyright (c) 2017, Daniel Kroeger

source bootstrap

if [[ -L ~/.config/openbox ]]; then
    unlink ~/.config/openbox
elif [[ -d ~/.config/openbox ]]; then
    echo -e "${ORANGE}Found existing ~/.config/openbox folder creating backup to ~/.config/openbox.bak${RESET}"
    mv ~/.config/openbox ~/.config/openbox.bak
fi

echo -n 'Copying .config/openbox folder'
cp -r $(pwd)/.config/openbox ~/.config/openbox
echo -e "${GREEN} done${RESET}"

echo
cowsay 'Tada - All done! You are now using dotfiles openbox config'
