#!/bin/bash -e
#
# Copyright (c) 2017, Daniel Kroeger

source bootstrap

DOTFILES_DIRECTORY="$(pwd)"

# We need sudo permission to install neovim
echo 'Asking you for sudo permissions to install neovim and plugins'
sudo -v
echo ''

echo -n 'Installing required build tools'
sudo apt-get install -y libtool libtool-bin autoconf automake cmake g++ \
    pkg-config unzip git python python3 python-pip python3-pip &> /dev/null
echo -e "${GREEN} done${RESET}"

if [[ ! -d "$HOME/Sourcecode/neovim" ]]; then
    mkdir -p $HOME/Sourcecode
    cd $HOME/Sourcecode

    echo -n 'Downloading neovim from github.com'
    git clone https://github.com/neovim/neovim.git &> /dev/null
    cd $HOME/Sourcecode/neovim
    echo -e "${GREEN} done${RESET}"
else
    echo -n 'Updating neovim'
    cd $HOME/Sourcecode/neovim
    git pull origin master &> /dev/null
    echo -e "${GREEN} done${RESET}"
fi

echo -n 'Compiling and installing neovim'
make clean &> /dev/null
make CMAKE_BUILD_TYPE=RelWithDebInfo &> /dev/null
sudo make install &> /dev/null
echo -e "${GREEN} done${RESET}"

echo -n 'Installing neovim python support'
sudo pip2 install --upgrade neovim &> /dev/null
sudo pip3 install --upgrade neovim &> /dev/null
echo -e "${GREEN} done${RESET}"

echo -n 'Activating neovim configuration'
if [[ -d "$HOME/.config/nvim" ]] && [[ ! -e $HOME/.config/nvim ]]; then
    mv $HOME/.config/nvim $HOME/.config/nvim.bak &> /dev/null
fi
cd $DOTFILES_DIRECTORY
ln -s $(pwd)/.config/nvim $HOME/.config/nvim &> /dev/null
echo -e "${GREEN} done${RESET}"

echo
cowsay 'You can now run nvim to start neovim'
