#!/bin/bash -e
#
# Copyright (c) 2017, Daniel Kroeger

source bootstrap

if [[ -L ~/.fonts ]]; then
    unlink ~/.fonts
elif [[ -d ~/.fonts ]]; then
    echo -e "${ORANGE}Found existing ~/.fonts folder creating backup to ~/.fonts.bak${RESET}"
    mv ~/.fonts ~/.fonts.bak
fi

echo -n 'Activating .fonts folder'
ln -s $(pwd)/.fonts ~/.fonts
echo -e "${GREEN} done${RESET}"

if [[ -L ~/.conky ]]; then
    unlink ~/.conky
elif [[ -d ~/.conky ]]; then
    echo -e "${ORANGE}Found existing ~/.conky folder creating backup to ~/.conky.bak${RESET}"
    mv ~/.conky ~/.conky.bak
fi

echo -n 'Activating .conky folder'
ln -s $(pwd)/.conky ~/.conky
echo -e "${GREEN} done${RESET}"


if [[ -L ~/.lua ]]; then
    unlink ~/.lua
elif [[ -d ~/.lua ]]; then
    echo -e "${ORANGE}Found existing ~/.lua folder creating backup to ~/.lua.bak${RESET}"
    mv ~/.lua ~/.lua.bak
fi

echo -n 'Activating .lua folder'
ln -s $(pwd)/.lua ~/.lua
echo -e "${GREEN} done${RESET}"

if [[ -L ~/.conkyrc ]]; then
    unlink ~/.conkyrc
elif [[ -f ~/.conkyrc ]]; then
    echo -e "${ORANGE}Found existing ~/.conkyrc file creating backup to ~/.conkyrc.bak${RESET}"
    mv ~/.conkyrc ~/.conkyrc.bak
fi

echo -n 'Activating .conkyrc file'
ln -s $(pwd)/.conkyrc ~/.conkyrc
echo -e "${GREEN} done${RESET}"

echo
cowsay 'Tada - All done! Run conky -c ~/.conkyrc to view your setup'
