#!/bin/bash
#
# Copyright (c) 2017, Daniel Kröger

# ANSI escape color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
RESET='\033[0m'

# Trap to notify user about failed command
trap 'echo -e "${RED} fail${RESET}"' ERR
