#!/bin/sh

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

headline()
{
    echo "\n${YELLOW}* ${GREEN}$1${NO_COLOR}"
}

warn()
{
    echo "${YELLOW}$1${NO_COLOR}"
}

# Greeting ####################################################################

echo "supersuer permissions required to install packages with apt"
sudo apt install -y cowsay
tput clear
cowsay -f tux "Setup kofrezo dotfiles"

# Install zsh and setup .zshrc ################################################

headline "Installing ZSH (Shell)"
sudo apt install -y zsh

headline "Setup .zshrc"
ZSHRC=$HOME/.zshrc
ln -s $PWD/.zshrc $ZSHRC | warn "$ZSHRC already exists!"

headline "Setup Oh-My-Zsh"
sudo apt install -y curl python3-pygments
if [ ! -d $HOME/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL \
https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    warn "Oh-My-Zsh already installed!"
fi

if [ -d $HOME/.ssh ]; then
    mkdir $HOME/.ssh
    chmod 0750 $HOME/.ssh
fi

# Install SDDM ################################################################

headline "Installing SDDM (Login Manager)"
sudo apt install -y sddm

headline "Configure SDDM (Login Manager)"
sudo cp -r $PWD/background.png \
    /usr/share/sddm/themes/debian-theme/background.png

# Install xinit ###############################################################

headline "Installing xinit"
sudo apt install -y xinit

# Ensure XDG_CONFIG_HOME variable is set ######################################

grep -q XDG_CONFIG_HOME $HOME/.profile
if [ $? -gt 0 ]; then
    echo "XDG_CONFIG_HOME=$HOME/.config" >> $HOME/.profile
fi

# compton #####################################################################

headline "Installing compton (Composite Manager)"
sudo apt install -y compton


# Install BSPWM and setup bspwmrc #############################################

headline "Installing BSPWM (Window Manger)"
sudo apt install -y bspwm

if [ ! -d $HOME/.config ]; then
    mkdir $HOME/.config
fi

headline "Setup bspwmrc"
BSPWM_DIR=$HOME/.config/bspwm
if [ ! -L $BSPWM_DIR ]; then
    ln -s $PWD/.config/bspwm $BSPWM_DIR
else
    warn "$BSPWM_DIR already exists!"
fi

# Install SXHKD and setup sxhkdrc #############################################

headline "Installing SXHKD (Keyboard Shortcuts)"
sudo apt install -y sxhkd

headline "Setup sxhkdrc"
SXHKD_DIR=$HOME/.config/sxhkd
if [ ! -L $SXHKD_DIR ]; then
    ln -s $PWD/.config/sxhkd $SXHKD_DIR
else
    warn "$SXHKD_DIR already exists!"
fi

# Install polybar and setup polybar config ####################################

headline "Installing polybar (Desktop Taskbar)"
sudo apt install -y polybar

headline "Setup polybar config"
POLYBAR_DIR=$HOME/.config/polybar
if [ ! -L $POLYBAR_DIR ]; then
    ln -s $PWD/.config/polybar $POLYBAR_DIR
else
    warn "$POLYBAR_DIR already exists!"
fi

# Install Fonts ###############################################################

headline "Installing additional fonts (JetBrains Mono)"
FONT_DIR=$HOME/.local/share/fonts
if [ ! -d $FONT_DIR ]; then
    mkdir -p $FONT_DIR
fi

if [ ! -L $FONT_DIR/JetBrainsMono ]; then
    ln -s $PWD/.local/share/fonts/JetBrainsMono $FONT_DIR/JetBrainsMono
    fc-cache -f -v
else
    warn "$FONT_DIR/JetBrainsMono already exists!"
fi

headline "Install additional fonts (Materialicons)"
if [ ! -L $FONT_DIR/Materialicons ]; then
    ln -s $PWD/.local/share/fonts/Materialicons $FONT_DIR/Materialicons
    fc-cache -f -v
else
    warn "$FONT_DIR/Materialicons already exists!"
fi

# Install feh #################################################################

headline "Installing feh (Background Image)"
sudo apt install -y feh

headline "Setup background image"
BACKGROUND_IMAGE=$HOME/background.png
ln -s $PWD/background.png $BACKGROUND_IMAGE | warn "$BACKGROUND_IMAGE already\
       	exists!"

# Install terminator ##########################################################

headline "Installing Terminator"
sudo apt install -y terminator

# Setup terminator
headline "Setup terminator config"
TERMINATOR_DIR=$HOME/.config/terminator
if [ ! -L $TERMINATOR_DIR ]; then
    ln -s $PWD/.config/terminator $TERMINATOR_DIR
else
    warn "$TERMINATOR_DIR already exists!"
fi

# Install pstree ##############################################################

headline "Installing psmisc (pstree)"
sudo apt install -y psmisc

# Install pyenv ###############################################################

headline "Installing pyenv (Simple Python Version Management)"
if [ ! -d $HOME/.pyenv ]; then
    curl https://pyenv.run | bash
else
    warn "pyenv already installed!"
fi

# Install pipenv ##############################################################

headline "Installing pipenv (Python Development Workflow)"
sudo apt install -y pipenv

# Install man pages ###########################################################

headline "Installing man pages"
sudo apt install -y man-db

# Vivaldi Browser #############################################################

headline "Installing Vivaldi (Internet Browser)"

VIVALDI_INSTALLED=$(dpkg -l | grep vivaldi-stable)
if [ -z "$VIVALDI_INSTALLED" ]; then
    curl -vs 2>&1 https://repo.vivaldi.com/archive/linux_signing_key.pub \
	| sudo apt-key add -
    sudo apt install -y software-properties-common
    sudo add-apt-repository \
	    'deb https://repo.vivaldi.com/archive/deb/ stable main'
    sudo apt update
    sudo apt install -y vivaldi-stable
else
    warn "Vivaldi is already installed!"
fi

# Spotify & Soundserver #######################################################

headline "Installing Pulseaudio"
sudo apt install -y pulseaudio pavucontrol

headline "Installing Spotify (ncspot)"
sudo apt install -y cargo
export PATH=$PATH:/usr/bin/cargo
cargo install ncspot

NCSPOT_DIR=$HOME/.config/ncspot
if [ ! -d $NCSPOT_DIR ]; then
    mkdir -p $NCSPOT_DIR
fi

NCSPOT_CONFIG=$HOME/.config/ncspot/config.toml
ln -s $PWD/.config/ncspot/config.toml $NCSPOT_CONFIG \
    | warn "$NCSPOT_CONFIG already exists!"

# vim #########################################################################

headline "Installing vim (Editor)"
sudo apt install -y vim

headline "Setup .vimrc"
VIMRC=$HOME/.vimrc
ln -s $PWD/.vimrc $VIMRC | warn "$VIMRC already exists"

# keepassx ####################################################################

headline "Installing keepassxc"
sudo apt install -y keepassxc

# Nextcloud ###################################################################

headline "Installing nextcloud"
sudo apt install -y nextcloud-desktop

# Gimp ########################################################################

headline "Installing gimp"
sudo apt install -y gimp
