#!/bin/sh

# Update dotfiles
git pull origin master

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

headline()
{
    echo "\n${YELLOW}* ${GREEN}$1${NO_COLOR}"
}

warn()
{
    echo "${YELLOW}$1${NO_COLOR}"
}

# Greeting
echo "sudo permissions required to install packages with apt"
sudo apt install -y cowsay
tput clear
cowsay -f tux "Setup kofrezo dotfiles"

# Install zsh and setup .zshrc
headline "Installing ZSH (Shell)"
sudo apt install -y zsh

headline "Setup .zshrc"
ZSHRC=$HOME/.zshrc
ln -s $PWD/.zshrc $ZSHRC | warn "$ZSHRC already exists!"

headline "Setup Oh-My-Zsh"
sudo apt install -y curl python3-pygments
if [ ! -d $HOME/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL \
https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    warn "Oh-My-Zsh already installed!"
fi

# Install SDDM
headline "Installing SDDM (Login Manager)"
sudo apt install -y sddm

# Install xinit
headline "Installing xinit"
sudo apt install -y xinit

# Ensure XDG_CONFIG_HOME variable is set
grep -q XDG_CONFIG_HOME $HOME/.profile
if [ $? -gt 0 ]; then
    echo "XDG_CONFIG_HOME=$HOME/.config" >> $HOME/.profile
fi

# Install BSPWM and setup bspwmrc
headline "Installing BSPWM (Window Manger)"
sudo apt install -y bspwm

headline "Setup bspwmrc"
BSPWM_DIR=$HOME/.config/bspwm
ln -s $PWD/.config/bspwm $BSPWM_DIR | warn "$BSPWM_DIR already exists!"

# Install SXHKD and setup sxhkdrc
headline "Installing SXHKD (Keyboard Shortcuts)"
sudo apt install -y sxhkd

headline "Setup sxhkdrc"
SXHKD_DIR=$HOME/.config/sxhkd
ln -s $PWD/.config/sxhkd $SXHKD_DIR | warn "$SXHKD_DIR already exists!"

# Install polybar and setup polybar config
headline "Installing polybar (Desktop Taskbar)"
sudo apt install -y -t buster-backports install polybar

# Install urxvt
headline "Installing urxvt (Terminal Emulator)"
sudo apt install -y rxvt-unicode  

# Install pstree
headline "Installing psmisc (pstree)"
sudo apt install -y psmisc

# Install pyenv
headline "Installing pyenv (Simple Python Version Management)"
if [ ! -d $HOME/.pyenv ]; then
    curl https://pyenv.run | bash
else
    warn "pyenv alread installed!"
fi

# Install pipenv
headline "Installing pipenv (Python Development Workflow)"
sudo apt install -y pipenv
