#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-1 --primary --right-of DP-2

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-2

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a terminator:shortcuts state=floating

# Launch task bar
$HOME/.config/polybar/launch.sh

# Set background image
feh --bg-fill $HOME/background.png

# Start Keepassxc
keepassxc &

# Give the user some time to enter the password in Keepassxc because this
# unlocks Secret Service Integration.
/bin/sh -c 'sleep 15 && nextcloud --background \
    --logfile $HOME/.logs/nextcloud.log' &

# Enable composite manager
compton &
