#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-4 --primary --right-of DP-2

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Launch task bar
$HOME/.config/polybar/launch.sh

# Set background image
feh --bg-center $HOME/background.jpg

# Enable composite manager
compton &
