[theme]
background = "#2B2B2B"
primary = "#999999"
secondary = "light black"
title = "#A9B7C6"
playing = "#A9B7C6"
playing_selected = "#A9B7C6"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#A9B7C6"
statusbar_bg = "#A9B7C6"
cmdline = "light white"
cmdline_bg = "black"

